spring.application.name=sportshop
spring.datasource.url=jdbc:postgresql://localhost:5432/sportshop
spring.datasource.username=postgres
spring.datasource.password=Lewski1914
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

